name: Build and test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux-bundled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule init && git submodule update --recursive
    - name: Install rust 1.65.0
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.65.0
        override: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build-windows-vcpkg:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: lukka/get-cmake@latest
    - name: Restore artifacts, or setup vcpkg (do not install any package)
      uses: lukka/run-vcpkg@v10
    - name: Run vcpkg
      uses: lukka/run-vcpkg@v4
      with:
        vcpkgArguments: 'darknet:x64-windows'
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
    - name: Checkout submodules
      run: git submodule init && git submodule update --recursive
    - name: Install rust 1.65.0
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.65.0
        override: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
